"""phase 2 gameweeks lineups scores

Revision ID: 1316e40eaa6c
Revises: 2b21abc8d362
Create Date: 2026-07-15 00:42:33.040036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1316e40eaa6c'
down_revision: Union[str, None] = '2b21abc8d362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameweeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'number', name='uq_gameweek_league_number')
    )
    op.create_index(op.f('ix_gameweeks_league_id'), 'gameweeks', ['league_id'], unique=False)
    op.create_table('lineup_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('bench_order', sa.Integer(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_vice', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'gameweek', 'player_id', name='uq_lineup_team_gw_player')
    )
    op.create_index(op.f('ix_lineup_slots_gameweek'), 'lineup_slots', ['gameweek'], unique=False)
    op.create_index(op.f('ix_lineup_slots_team_id'), 'lineup_slots', ['team_id'], unique=False)
    op.create_table('team_gameweek_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'gameweek', name='uq_score_team_gameweek')
    )
    op.create_index(op.f('ix_team_gameweek_scores_gameweek'), 'team_gameweek_scores', ['gameweek'], unique=False)
    op.create_index(op.f('ix_team_gameweek_scores_team_id'), 'team_gameweek_scores', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_gameweek_scores_team_id'), table_name='team_gameweek_scores')
    op.drop_index(op.f('ix_team_gameweek_scores_gameweek'), table_name='team_gameweek_scores')
    op.drop_table('team_gameweek_scores')
    op.drop_index(op.f('ix_lineup_slots_team_id'), table_name='lineup_slots')
    op.drop_index(op.f('ix_lineup_slots_gameweek'), table_name='lineup_slots')
    op.drop_table('lineup_slots')
    op.drop_index(op.f('ix_gameweeks_league_id'), table_name='gameweeks')
    op.drop_table('gameweeks')
    # ### end Alembic commands ###
