"""phase 1 fantasy leagues teams drafts picks

Revision ID: 2b21abc8d362
Revises: 3e0c5d4dff40
Create Date: 2026-07-14 19:31:50.047887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b21abc8d362'
down_revision: Union[str, None] = '3e0c5d4dff40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fantasy_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=12), nullable=False),
    sa.Column('commissioner_id', sa.Integer(), nullable=False),
    sa.Column('pick_timer_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commissioner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fantasy_leagues_invite_code'), 'fantasy_leagues', ['invite_code'], unique=True)
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_league_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rounds', sa.Integer(), nullable=False),
    sa.Column('draft_order', sa.JSON(), nullable=False),
    sa.Column('current_pick_index', sa.Integer(), nullable=False),
    sa.Column('current_pick_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fantasy_league_id'], ['fantasy_leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drafts_fantasy_league_id'), 'drafts', ['fantasy_league_id'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fantasy_league_id'], ['fantasy_leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fantasy_league_id', 'user_id', name='uq_team_league_user')
    )
    op.create_index(op.f('ix_teams_fantasy_league_id'), 'teams', ['fantasy_league_id'], unique=False)
    op.create_index(op.f('ix_teams_user_id'), 'teams', ['user_id'], unique=False)
    op.create_table('draft_picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'pick_number', name='uq_draft_pick_number'),
    sa.UniqueConstraint('draft_id', 'player_id', name='uq_draft_player')
    )
    op.create_index(op.f('ix_draft_picks_draft_id'), 'draft_picks', ['draft_id'], unique=False)
    op.create_index(op.f('ix_draft_picks_team_id'), 'draft_picks', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_draft_picks_team_id'), table_name='draft_picks')
    op.drop_index(op.f('ix_draft_picks_draft_id'), table_name='draft_picks')
    op.drop_table('draft_picks')
    op.drop_index(op.f('ix_teams_user_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_fantasy_league_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_drafts_fantasy_league_id'), table_name='drafts')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_fantasy_leagues_invite_code'), table_name='fantasy_leagues')
    op.drop_table('fantasy_leagues')
    # ### end Alembic commands ###
