"""phase 0 initial tables

Revision ID: 3e0c5d4dff40
Revises: 
Create Date: 2026-07-14 19:01:35.551360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0c5d4dff40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('club', sa.String(length=80), nullable=False),
    sa.Column('position', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=True),
    sa.Column('source_a_id', sa.String(length=50), nullable=True),
    sa.Column('source_b_id', sa.String(length=50), nullable=True),
    sa.Column('tm_id', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fpl_id')
    )
    op.create_index(op.f('ix_players_club'), 'players', ['club'], unique=False)
    op.create_index(op.f('ix_players_league_id'), 'players', ['league_id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_table('player_stats_weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('clean_sheets', sa.Integer(), nullable=False),
    sa.Column('goals_conceded', sa.Integer(), nullable=False),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('own_goals', sa.Integer(), nullable=False),
    sa.Column('penalties_missed', sa.Integer(), nullable=False),
    sa.Column('penalties_saved', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=True),
    sa.Column('xa', sa.Float(), nullable=True),
    sa.Column('npxg', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('composite_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'gameweek', name='uq_player_gameweek')
    )
    op.create_index(op.f('ix_player_stats_weekly_gameweek'), 'player_stats_weekly', ['gameweek'], unique=False)
    op.create_index(op.f('ix_player_stats_weekly_player_id'), 'player_stats_weekly', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_weekly_player_id'), table_name='player_stats_weekly')
    op.drop_index(op.f('ix_player_stats_weekly_gameweek'), table_name='player_stats_weekly')
    op.drop_table('player_stats_weekly')
    op.drop_index(op.f('ix_players_position'), table_name='players')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_league_id'), table_name='players')
    op.drop_index(op.f('ix_players_club'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('leagues')
    # ### end Alembic commands ###
