"""phase 3 trades votes notifications

Revision ID: 6cbfff6c37ac
Revises: 1316e40eaa6c
Create Date: 2026-07-15 10:30:48.311225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cbfff6c37ac'
down_revision: Union[str, None] = '1316e40eaa6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fantasy_league_id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('proposer_team_id', sa.Integer(), nullable=False),
    sa.Column('receiver_team_id', sa.Integer(), nullable=False),
    sa.Column('players_from_proposer', sa.JSON(), nullable=False),
    sa.Column('players_from_receiver', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fairness_ratio', sa.Float(), nullable=True),
    sa.Column('voting_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['fantasy_league_id'], ['fantasy_leagues.id'], ),
    sa.ForeignKeyConstraint(['proposer_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['receiver_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_fantasy_league_id'), 'trades', ['fantasy_league_id'], unique=False)
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.create_table('trade_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('approve', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'team_id', name='uq_trade_vote_team')
    )
    op.create_index(op.f('ix_trade_votes_trade_id'), 'trade_votes', ['trade_id'], unique=False)
    op.add_column('fantasy_leagues', sa.Column('trade_window_days', sa.Integer(), server_default='3', nullable=False))
    op.add_column('fantasy_leagues', sa.Column('max_trades_per_period', sa.Integer(), server_default='2', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fantasy_leagues', 'max_trades_per_period')
    op.drop_column('fantasy_leagues', 'trade_window_days')
    op.drop_index(op.f('ix_trade_votes_trade_id'), table_name='trade_votes')
    op.drop_table('trade_votes')
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.drop_index(op.f('ix_trades_fantasy_league_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
